ViewModels/ManageUser/AddUserToRoleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MohamadShop.ViewModels.ManageUser
{
    public class AddUserToRoleViewModel
    {
        public AddUserToRoleViewModel()
        {
            UserRoles = new List<UserRolesViewModel>();
        }

        public string UserId { get; set; }

        public List<UserRolesViewModel> UserRoles { get; set; }
    }

    public class UserRolesViewModel
    {
        public string RoleName { get; set; }
        public bool IsSelected { get; set; }
    }
}

ViewModels/ManageUser/IndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MohamadShop.ViewModels.ManageUser
{
    public class IndexViewModel
    {

        public string Id { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }

    }
}

Controllers/ManageUserController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MohamadShop.ViewModels.ManageUser;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MohamadShop.Controllers
{
    public class ManageUserController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public ManageUserController(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var model = _userManager.Users
                .Select(u => new IndexViewModel()
                { Id = u.Id, UserName = u.UserName, Email = u.Email }).ToList();
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();
            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();

            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditUser(string id, string userName)
        {
            if (string.IsNullOrEmpty(id) || string.IsNullOrEmpty(userName)) return NotFound();
            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();
            user.UserName = userName;
            var result = await _userManager.UpdateAsync(user);

            if (result.Succeeded) return RedirectToAction("index");

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(user);
        }

        [HttpGet]
        public async Task<IActionResult> AddUserToRole(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();

            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();
            var roles = _roleManager.Roles.ToList();
            var model = new AddUserToRoleViewModel() { UserId = id };

            foreach (var role in roles)
            {
                if (!await _userManager.IsInRoleAsync(user, role.Name))
                {
                    model.UserRoles.Add(new UserRolesViewModel()
                    {
                        RoleName = role.Name
                    });
                }
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddUserToRole(AddUserToRoleViewModel model)
        {
            if (model == null) return NotFound();
            var user = await _userManager.FindByIdAsync(model.UserId);
            if (user == null) return NotFound();
            var requestRoles = model.UserRoles.Where(r => r.IsSelected)
                .Select(u => u.RoleName)
                .ToList();
            var result = await _userManager.AddToRolesAsync(user, requestRoles);

            if (result.Succeeded) return RedirectToAction("index");

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> RemoveUserFromRole(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();
            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();
            var roles = _roleManager.Roles.ToList();
            var model = new AddUserToRoleViewModel() { UserId = id };

            foreach (var role in roles)
            {
                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    model.UserRoles.Add(new UserRolesViewModel()
                    {
                        RoleName = role.Name
                    });
                }
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> RemoveUserFromRole(AddUserToRoleViewModel model)
        {
            if (model == null) return NotFound();
            var user = await _userManager.FindByIdAsync(model.UserId);
            if (user == null) return NotFound();
            var requestRoles = model.UserRoles.Where(r => r.IsSelected)
                .Select(u => u.RoleName)
                .ToList();
            var result = await _userManager.RemoveFromRolesAsync(user, requestRoles);

            if (result.Succeeded) return RedirectToAction("index");

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteUser(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();
            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();
            await _userManager.DeleteAsync(user);

            return RedirectToAction("Index");
        }
    }
}

Views/ManageUser/AddUserToRole.cshtml
@model MohamadShop.ViewModels.ManageUser.AddUserToRoleViewModel
  
}

<h1>AddUserToRole</h1>

<div class="container">

    @if (!Model.UserRoles.Any())
    {
        <h1>هیچ مقامی یافت نشد</h1>
    }
    else
    {
        <form asp-controller="ManageUser" asp-action="AddUserToRole" method="post">
            <div asp-validation-summary="ModelOnly"></div>

            @for (int i = 0; i < Model.UserRoles.Count; i++)
            {
                <div class="form-group">
                    <input asp-for="@Model.UserRoles[i].IsSelected" />
                    <label>@Model.UserRoles[i].RoleName</label>

                    <input type="hidden" asp-for="@Model.UserRoles[i].RoleName" />
                </div>
            }
            <input type="hidden" asp-for="@Model.UserId" />
            <button class="btn btn-primary" type="submit">Submit</button>
        </form>
    }

</div>

Views/ManageUser/EditUser.cshtml
@model Microsoft.AspNetCore.Identity.IdentityUser
@{
    ViewData["Title"] = "EditUser";
}

<h1>EditUser</h1>
<div class="container">

    <form asp-controller="ManageUser" asp-action="EditUser" method="post">
        <div asp-validation-summary="ModelOnly"></div>

        <div class="form-group">
            <label class="control-label" asp-for="UserName"></label>
            <input class="form-control" asp-for="UserName" />
        </div>

        <input type="hidden" asp-for="Id" />

        <button class="btn btn-primary" type="submit">Submit</button>
    </form>
    </div>

Views/ManageUser/Index.cshtml
@model List<MohamadShop.ViewModels.ManageUser.IndexViewModel>
@{
    ViewData["Title"] = "Index";
}

<div class="container">

    @if (!Model.Any())
    {
        <h1>کاربری یافت نشد</h1>
    }
    else
    {
        for (int i = 0; i < Model.Count; i++)
        {
            <div class="card mt-2">
                <div class="card-header">
                    User Name : <b>@Model[i].UserName</b>
                </div>
                <div class="card-body">
                    User Email : <b>@Model[i].Email</b>
                </div>
                <div class="card-footer">
                    <form asp-controller="ManageUser" asp-action="DeleteUser" asp-route-id="@Model[i].Id" method="post">

                        <a asp-controller="ManageUser" asp-action="EditUser" asp-route-id="@Model[i].Id"
                           class="btn btn-primary">Edit Username</a>

                        <a asp-controller="ManageUser" asp-action="AddUserToRole" asp-route-id="@Model[i].Id"
                           class="btn btn-primary">Add to role</a>
                        <a asp-controller="ManageUser" asp-action="RemoveUserFromRole" asp-route-id="@Model[i].Id"
                           class="btn btn-danger">Remove From role</a>

                        <button type="submit" class="btn btn-danger">Delete user</button>
                    </form>
                </div>
            </div>
        }
    }
    </div>

Views/ManageUser/RemoveUserFromRole.cshtml
@model MohamadShop.ViewModels.ManageUser.AddUserToRoleViewModel
@{
    ViewData["Title"] = "DeleteUserToRole";
}

<h1>DeleteUserToRole</h1>
<div class="container">

    <form asp-controller="ManageUser" asp-action="RemoveUserFromRole" method="post">
        <div asp-validation-summary="ModelOnly"></div>
        @if (!Model.UserRoles.Any())
        {
            <h1>هیچ مقامی یافت نشد</h1>
        }
        else
        {
            for (int i = 0; i < Model.UserRoles.Count; i++)
            {
                <div class="form-group">
                    <input asp-for="@Model.UserRoles[i].IsSelected" />
                    <label>@Model.UserRoles[i].RoleName</label>

                    <input type="hidden" asp-for="@Model.UserRoles[i].RoleName" />
                </div>
            }
        }

        <input type="hidden" asp-for="@Model.UserId" />
        <button class="btn btn-primary" type="submit">Submit</button>
    </form>
    </div>